--/*Registro 095 Fin Comprobante

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR(10)
SET @NROLOT = '1'
SET @CODTRA = 'USR_PAPFRA'
SET @FCHEMI = ''
SET @FCHENT = ''
SET @FCHPAG = ''
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'095' FLD002,
'CUIT' FLD003,
REPLACE((SELECT NORMALVALUE FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004, 
'@@@@@@' FLD005, 
SUM (CONVERT(NUMERIC,INRMSI_FLD008)) FLD006, /*CJRMVI_IMPORT DEL REGISTRO B*/
COUNT (INRMSI_FLD007) FLD007,
(SELECT CONVERT(VARCHAR,COUNT(*)+1)  FROM INRMSI 
WHERE 
INRMSI_CODTRA = @CODTRA AND
INRMSI_NROLOT = @NROLOT) FLD008, -- SUMATORIA DE REGISTROS
SPACE (790) FLD009,
'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ' FLD080 /*Orden de Registro*/

FROM INRMSI 
WHERE INRMSI_CODTRA = @CODTRA 
AND INRMSI_TIPREG = 'B' 
AND INRMSI_NROLOT = @NROLOT
