--/* Registro 025

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6),@PERFIN VARCHAR(1),@CHTIPO VARCHAR(1) ,@ABTIPO VARCHAR(1)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
SET @PERFIN = 'N'
SET @CHTIPO = '1'
SET @ABTIPO = '0'
--*/


SELECT
'0306' FLD001,
'025' FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
SPACE (15) FLD006,
REPLACE(CONVERT(VARCHAR,CJRMVI_NROFOR),' ','') FLD007,
REPLACE(SUM(CJRMVI_IMPORT),'.','')  FLD008,
SPACE (125) FLD009,
ISNULL(@PERFIN,SPACE(1)) FLD010, /*IPERFIM: No se utiliza*/ 
SPACE (58) FLD011,
SPACE (22) FLD012, /*CBU. Se informa en el registro 90*/
REPLACE(
CASE
WHEN @FCHPAG = '' THEN CONVERT(VARCHAR,GETDATE(),112) 
ELSE CONVERT(VARCHAR,@FCHPAG,112) END ,'-','') FLD013, /*Fecha de pago*/
(CASE WHEN (SELECT COUNT(*) FROM  CJRMVI C1
			INNER JOIN
			GRCCOH ON GRCCOH_TIPCPT = C1.CJRMVI_TIPCPT AND
			GRCCOH_CODCPT = C1.CJRMVI_CODCPT AND
			GRCCOH_MODCPT = C1.CJRMVI_MODCPT 
			AND GRCCOH_TIPCPT = 'B'
			WHERE 
				  C1.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP
				  AND C1.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR
				  AND C1.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR
				  AND C1.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR

			)>1 then '9' 
ELSE 
	CASE WHEN (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			WHERE GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	'CH'
	ELSE 'AB' END
END) FLD014, /*Forma de pago*/
SPACE (1) FLD015,
(CASE WHEN (SELECT COUNT(*) FROM  CJRMVI C1
			INNER JOIN
			GRCCOH ON GRCCOH_TIPCPT = C1.CJRMVI_TIPCPT AND
			GRCCOH_CODCPT = C1.CJRMVI_CODCPT AND
			GRCCOH_MODCPT = C1.CJRMVI_MODCPT 
			AND GRCCOH_TIPCPT = 'B'
			WHERE 
				  C1.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP
				  AND C1.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR
				  AND C1.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR
				  AND C1.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR

			)>1 then '9' 
ELSE 
	CASE WHEN (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			WHERE GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	@CHTIPO 
	ELSE @ABTIPO END
END) FLD016, 
SPACE (1) FLD017,
case when (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			where GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	RIGHT(REPLACE(CJRMVI_CHEQUE,' ','')+'0000000000000',13)
	ElSE SPACE(13)  END FLD018, -- NRO CHEQUE  --Número de cheque emitido
SPACE (6) FLD019,
SPACE (40) FLD0120,
SPACE (506) FLD021,
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,3) FLD080 /*Orden de Registro*/

FROM
CJRMVI INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN GRCCOH ON 
GRCCOH_CODCPT = CJRMVI_CODCPT AND
GRCCOH_TIPCPT = CJRMVI_TIPCPT AND
GRCCOH_MODCPT = CJRMVI_MODCPT
INNER JOIN INRMSI on 
INRMSI_CODTRA = @CODTRA AND
INRMSI_NROLOT = @NROLOT AND
INRMSI_TIPREG = 'A' AND
INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE
GRCCOH_PIDCHE = 
(CASE WHEN (@ENVCHE = 'S' AND @ENVTRA = 'S') THEN
GRCCOH_PIDCHE
ELSE
	(CASE WHEN (@ENVCHE = 'S' AND @ENVTRA = 'N') THEN
		'S'
	ELSE	
		'N'
	END)
END) AND
CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY CJRMVI_CHEQUE,
		CJRMVI.CJRMVI_NROFOR,
		GRCCOH.GRCCOH_PIDCHE,
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_CODCPT,
		CJRMVI.CJRMVI_TIPCPT,
		CJRMVI.CJRMVI_MODCPT