--/* Registro 040

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'040' FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
SPACE(2) FLD006,
'' FLD007,
SPACE(25) FLD008,
'DB' FLD009, 
SPACE(1) FLD010, /*TIPO-COMP-MINUTA*/ 
SPACE(12) FLD011, /*NRO-COMP-MINUTA */
SPACE(13) FLD012, /*IMPORTE-COMP-MINUTA*/
SPACE(2) FLD013, /*COD-IMPUESTO */
SPACE(5) FLD014, /*ALICUOTA-1-MINUTA */
SPACE(13) FLD015, /*IMPORTE-1-MINUTA */
SPACE(5) FLD016, /*ALICUOTA-1-MINUTA */
SPACE(13) FLD017, /*IMPORTE-1-MINUTA */
SPACE(718) FLD018, /*FILLER */
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,5) FLD080 /*Orden de Registro*/

FROM CJRMVI INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN INRMSI ON 
INRMSI_CODTRA = @CODTRA 
AND INRMSI_NROLOT = @NROLOT
AND INRMSI_TIPREG = 'A' 
AND INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE 
CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY CJRMVI_CHEQUE,
		CJRMVI.CJRMVI_NROFOR,
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_CODCPT,
		CJRMVI.CJRMVI_TIPCPT,
		CJRMVI.CJRMVI_MODCPT