--/* Registro 010
DECLARE @CODEMP VARCHAR (6), @FCHEMI DATE, @FCHENT DATE, @FCHPAG DATE, @CODTRA VARCHAR (12), @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @NROLOT VARCHAR (3),@CHTIPO VARCHAR(1) ,@ABTIPO VARCHAR(1)
SET @NROLOT = '59'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
SET @CHTIPO = '1'
SET @ABTIPO = '0'
--*/

SELECT 
'0306' FLD001,
'010' FLD002,
'CUIT' FLD003,
REPLACE((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
REPLICATE ('0',6) FLD005,
CJTCTA_MONEXT FLD006,
CAST(REPLACE(Sum(CJRMVI_IMPORT),'.','') AS VARCHAR) FLD007,
(CASE WHEN (SELECT COUNT(*) FROM  CJRMVI C1
			INNER JOIN
			GRCCOH ON GRCCOH_TIPCPT = C1.CJRMVI_TIPCPT AND
			GRCCOH_CODCPT = C1.CJRMVI_CODCPT AND
			GRCCOH_MODCPT = C1.CJRMVI_MODCPT 
			AND GRCCOH_TIPCPT = 'B'
			WHERE 
				  C1.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP
				  AND C1.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR
				  AND C1.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR
				  AND C1.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR

			)>1 then '99'
ELSE  
	CASE WHEN (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			WHERE GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	'CH' 
	ELSE 'AB' END
END) FLD008,
REPLICATE ('0',1) FLD009,
(CASE WHEN (SELECT COUNT(*) FROM  CJRMVI C1
			INNER JOIN
			GRCCOH ON GRCCOH_TIPCPT = C1.CJRMVI_TIPCPT AND
			GRCCOH_CODCPT = C1.CJRMVI_CODCPT AND
			GRCCOH_MODCPT = C1.CJRMVI_MODCPT 
			AND GRCCOH_TIPCPT = 'B'
			WHERE 
				  C1.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP
				  AND C1.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR
				  AND C1.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR
				  AND C1.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR

			)>1 then '9' 
ELSE 
	CASE WHEN (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			WHERE GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	@CHTIPO 
	ELSE @ABTIPO END
END) FLD010,
'0' FLD011,
Replace(CASE
WHEN @FCHEMI = '' THEN CONVERT(VARCHAR,GETDATE(),112) 
ELSE CONVERT(VARCHAR,@FCHEMI,112) END,'-','') FLD012, /*FECHA-EMISION*/
Replace(CASE 
WHEN @FCHENT = '' THEN CONVERT(VARCHAR,
				(SELECT C2.CJRMVI_FCHVNC FROM CJRMVI C2
				 WHERE   C2.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR AND
						C2.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR AND
						C2.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR AND
						C2.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP),112) 
ELSE CONVERT(VARCHAR,@FCHENT,112) END,'-','') FLD013, /*FECHA-ENTREGA*/ 
Replace(CASE
WHEN @FCHPAG = '' THEN CONVERT(VARCHAR,
				(SELECT C2.CJRMVI_FCHVNC FROM CJRMVI C2
				 WHERE   C2.CJRMVI_MODFOR = CJRMVI.CJRMVI_MODFOR AND
						C2.CJRMVI_CODFOR = CJRMVI.CJRMVI_CODFOR AND
						C2.CJRMVI_NROFOR = CJRMVI.CJRMVI_NROFOR AND
						C2.CJRMVI_CODEMP = CJRMVI.CJRMVI_CODEMP),112)
ELSE CONVERT(VARCHAR,@FCHENT,112) END,'-','') FLD014, /*FECHA-PAGO*/ 
'0017' FLD015,
SUBSTRING(CJTCTA_CLABCO,4,4) FLD016, /*SUCURSAL CUENTA DEBITO*/
SUBSTRING(CJTCTA_CLABCO,8,1) FLD017, /*Digito verificador. Son dos caracteres???????????????????*/
CJRMVI_CTACTE FLD018, /*EQUIV 01 para CC, 02 para CA*/ /* COMPLETAR  EQUIVALENCIA!!! */
CJTCTA_MONEXT FLD019,
RIGHT(CJTCTA_CLABCO,7) FLD020, /*NRO CTA DE DEBITO*/
(SELECT CONVERT(VARCHAR,COUNT(*)+1)  FROM INRMSI 
WHERE 
INRMSI_CODTRA = @CODTRA AND
INRMSI_NROLOT = @NROLOT AND	
INRMSI_TIPREG='A') FLD021,
@ENVCHE FLD022,
SPACE (4) FLD023,
SPACE (6) FLD024,
SPACE (1) FLD025,
RIGHT(SPACE(12)+'PAPFRA.txt',12) FLD26,
''  FLD027,
SPACE (20) FLD028, -- CONTRATO PROV
SPACE (698) FLD029,
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) FLD080 /*Orden de Registro*/

FROM
CJRMVI 
INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN GRCCOH ON 
GRCCOH_CODCPT = CJRMVI_CODCPT AND
GRCCOH_TIPCPT = CJRMVI_TIPCPT AND
GRCCOH_MODCPT = CJRMVI_MODCPT
INNER JOIN CJTCTA ON
CJRMVI_CTACTE = CJTCTA_CTACTE

WHERE
GRCCOH_PIDCHE = 
(CASE WHEN (@ENVCHE = 'S' AND @ENVTRA = 'S') THEN
GRCCOH_PIDCHE
ELSE
	(CASE WHEN (@ENVCHE = 'S' AND @ENVTRA = 'N') THEN
		'S'
	ELSE	
		'N'
	END)
END) AND
CJRMVI_CODBCO = '017' AND
CJRMVI_CODEMP =  @CODEMP
group by CJRMVI_CODFOR,
		 CJRMVI_NROFOR, 
		 CJTCTA_MONEXT,
		 CJTCTA.CJTCTA_CLABCO,
		 CJRMVI.CJRMVI_MODCPT,
		 CJRMVI.CJRMVI_CODCPT,
		 CJRMVI.CJRMVI_TIPCPT,
		 CJRMVI.CJRMVI_CTACTE,
		 CJRMVI.CJRMVI_CODEMP, 
		 CJRMVI.CJRMVI_MODFOR,
		 CJRMVI_CODBCO
ORDER BY CJRMVI_CODFOR DESC ,CJRMVI_NROFOR DESC
