--/*Registro 080

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @CODEMP VARCHAR (6)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'080'  FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
PVROPH_CODRET FLD006,
PVMPRH_JURISD FLD007,
PVROPH_NROAPL FLD008,
CONVERT(VARCHAR,PVROPH_FCHMOV,112) FLD009,
SPACE(25)  FLD010,
CJRMVI.CJRMVI_TIPCPT FLD011,
CJRMVI.CJRMVI_NROFOR FLD012,
REPLACE(CJRMVI.CJRMVI_IMPORT,'.','') FLD013,
SPACE(13) FLD014,
SPACE(5) FLD015,
SPACE(13) FLD016,
SPACE(5) FLD017,
SPACE(13) FLD018,
SPACE(5) FLD019,
SPACE(13) FLD020,
'DB' FLD021,
REPLICATE('0',15) FLD022,
SPACE(647)  FLD023,
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,5) FLD080 /*Orden de Registro*/

FROM CJRMVI 
INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN PVROPH ON CJRMVI_CODEMP = PVROPH_CODEMP
			  AND CJRMVI_MODFOR = 'CJ'
			  AND CJRMVI_CODFOR = PVROPH_CODFOR
			  AND CJRMVI_NROFOR = PVROPH_NROFOR
			  AND PVROPH_TIPRET = 'RB'

INNER JOIN INRMSI ON 
INRMSI_CODTRA = @CODTRA 
AND INRMSI_NROLOT = @NROLOT
AND INRMSI_TIPREG = 'A' 
AND INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE 
CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY 
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_NROFOR,
		CJRMVI.CJRMVI_TIPCPT,
		PVMPRH.PVMPRH_JURISD,
		PVROPH.PVROPH_FCHMOV,
		PVROPH.PVROPH_IMPRET,
		PVROPH.PVROPH_CODRET,
		PVROPH.PVROPH_NROAPL,
		CJRMVI.CJRMVI_IMPORT
		