--/* Registro 060 

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'060' FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
PVROPH_NROAPL FLD006,
'' FLD007,
RIGHT(REPLICATE('0',11)+ISNULL(CASE WHEN PVMPRH_TIPDOC = 'INBR' OR  PVMPRH_TIPDOC = 'IBRL'THEN PVMPRH_NRODOC
	 WHEN PVMPRH_TIPDO1 = 'INBR' OR  PVMPRH_TIPDO1 = 'IBRL'THEN PVMPRH_NRODO1	
	 WHEN PVMPRH_TIPDO2 = 'INBR' OR  PVMPRH_TIPDO2 = 'IBRL'THEN PVMPRH_NRODO2	
	 WHEN PVMPRH_TIPDO3 = 'INBR' OR  PVMPRH_TIPDO3 = 'IBRL'THEN PVMPRH_NRODO3	
	 END,SPACE(11)),11)  FLD008,
SPACE(791) FLD009, 
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,5) FLD080 /*Orden de Registro*/

FROM CJRMVI 
INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN PVROPH ON CJRMVI_CODEMP = PVROPH_CODEMP
			  AND CJRMVI_MODFOR = 'CJ'
			  AND CJRMVI_CODFOR = PVROPH_CODFOR
			  AND CJRMVI_NROFOR = PVROPH_NROFOR
			  AND PVROPH_TIPRET = 'RB'

INNER JOIN INRMSI ON 
INRMSI_CODTRA = @CODTRA 
AND INRMSI_NROLOT = @NROLOT
AND INRMSI_TIPREG = 'A' 
AND INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE 
CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY CJRMVI_CHEQUE,
		CJRMVI.CJRMVI_NROFOR,
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_CODCPT,
		CJRMVI.CJRMVI_TIPCPT,
		CJRMVI.CJRMVI_MODCPT,
		PVROPH_IMPRET,
		PVROPH_NROAPL,
		PVMPRH_TIPDOC,
		PVMPRH_TIPDO1,
		PVMPRH_TIPDO2,
		PVMPRH_TIPDO3,
		PVMPRH_NRODOC,
		PVMPRH_NRODO1,
		PVMPRH_NRODO2,
		PVMPRH_NRODO3


