--/* Registro 030 Fin de comprobante

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'030' FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
'R' FLD006,
SPACE(753) FLD007,
RIGHT(CJRMVI_CODCPT+SPACE(49),49) FLD008,
ISNULL((SELECT REPLACE(Sum(PVROPH_IMPRET),'.','') FROM PVROPH 
WHERE CJRMVI_CODEMP = PVROPH_CODEMP
AND CJRMVI_MODFOR = 'CJ'
AND CJRMVI_CODFOR = PVROPH_CODFOR
AND CJRMVI_NROFOR = PVROPH_NROFOR),SPACE(13)) FLD009, 
'DB' FLD010, --Código de Débito DB o Crédito CR del concepto /Equiv??/
SPACE(850) FLD011,
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,5) FLD080 /*Orden de Registro*/

FROM CJRMVI INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN INRMSI ON 
INRMSI_CODTRA = @CODTRA 
AND INRMSI_NROLOT = @NROLOT
AND INRMSI_TIPREG = 'A' 
AND INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE 
	CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY
		CJRMVI.CJRMVI_NROFOR,
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_CODCPT,
		CJRMVI.CJRMVI_TIPCPT,
		CJRMVI.CJRMVI_MODCPT