--/* Registro 020

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6), @SUCENT VARCHAR (4), @INFRET VARCHAR (1),@PERFIN VARCHAR(1),@CUIDES VARCHAR(13),@NOMDES VARCHAR(40),@CLIAJE VARCHAR(1)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT' 
SET @SUCENT = '0001' 
SET @INFRET = 'S'
SET @PERFIN = 'N'
SET @CUIDES = ''
SET @CLIAJE = 'N'
SET @NOMDES = ''
--*/

SELECT 
'0306' FLD001,
'020' FLD002,
'CUIT' FLD003,
 REPLACE((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
 PVMPRH_NROCTA FLD006,
CONVERT(VARCHAR,CJRMVI_NROFOR) FLD007,
REPLACE(SUM(CJRMVI_IMPORT),'.','')  FLD008,
CASE WHEN ISNULL(@INFRET,'N') = 'S' 
	 THEN
		RIGHT('               '
			+ISNULL((SELECT CONVERT(VARCHAR,PVROPH_NROGEN) FROM PVROPH 
					 WHERE CJRMVI_CODEMP = PVROPH_CODEMP
					 AND CJRMVI_MODFOR = 'CJ'
					 AND CJRMVI_CODFOR = PVROPH_CODFOR
					 AND CJRMVI_NROFOR = PVROPH_NROFOR
					 AND PVROPH_TIPRET = 'RG'),''),14) 
		ElSE
		SPACE(14)
 END	 FLD009,/*NRO-CERT-RET-GANANCIAS*/
SPACE (30) FLD010, /*REGIMEN-GANANCIAS OPC*/
isnull(RIGHT('000000000000000'+
	REPLACE(CONVERT(VARCHAR,(CASE 
		WHEN ISNULL(@INFRET,'N') = 'S' 
		THEN (SELECT SUM(PVROPH_IMPRET) FROM PVROPH 
			  WHERE CJRMVI_CODEMP = PVROPH_CODEMP
			  AND CJRMVI_MODFOR = 'CJ'
			  AND CJRMVI_CODFOR = PVROPH_CODFOR
			  AND CJRMVI_NROFOR = PVROPH_NROFOR
			  AND PVROPH_TIPRET = 'RG')
	 ELSE ''END)),'.',''),13),SPACE(13)) FLD011, /*Sólo si la empresa imprimirá comprobante de retención. Si es libre no se informa*/
isnull(RIGHT('0000000000000000'+
	REPLACE(CONVERT(VARCHAR,(CASE 
		WHEN ISNULL(@INFRET,'N') = 'S' 
		THEN (SELECT PVROPH_IMPRET FROM PVROPH 
			  WHERE CJRMVI_CODEMP = PVROPH_CODEMP
			  AND CJRMVI_MODFOR = 'CJ'
			  AND CJRMVI_CODFOR = PVROPH_CODFOR
			  AND CJRMVI_NROFOR = PVROPH_NROFOR
			  AND PVROPH_TIPRET = 'RI')
	 ELSE ''END)),'.',''),14),SPACE(14)) FLD012,  /*Sólo si la empresa imprimirá comprobante de retención. Si es libre no se informa*/
SPACE (30) FLD013, /*REGIMEN-IVA opc*/
RIGHT(SPACE(15)+'PAPFRA.txt',15) FLD014, 
SPACE (8) FLD015, 
SPACE (1) FLD016, 
ISNULL(@PERFIN,SPACE(1)) FLD017, /*IPERMFIN*/
@CLIAJE  FLD018, 
ISNULL(@CUIDES,SPACE(13)) FLD019, /*Se completa si el destinatario del cheque es distinto al de la minuta.*/
ISNULL(@NOMDES,SPACE(40))  FLD020, /*Se completa si el destinatario del cheque es distinto al de la minuta.*/
PVMPRH_TIPDOC FLD021,/*EQUIV registro 090*/
PVMPRH_NRODOC FLD022,
@SUCENT FLD023, /*Sucursal de entrega (Parametro)*/
SPACE (8) FLD024, /*INFORMADO EN EL CAMPO 13 DE LA CABECERA*/
SPACE (8) FLD025, /*INFORMADO EN EL CAMPO 14 DE LA CABECERA*/
SPACE (2) FLD026, /*INFORMADO EN EL CAMPO 8 DE LA CABECERA*/
SPACE (1) FLD027, /*INFORMADO EN EL CAMPO 9 DE LA CABECERA*/
REPLICATE ('0',1) FLD028, 
REPLICATE ('0',1) FLD029,
case when (SELECT GRCCOH_PIDCHE FROM GRCCOH 
			where GRCCOH_CODCPT = CJRMVI.CJRMVI_CODCPT AND
			GRCCOH_TIPCPT = CJRMVI.CJRMVI_TIPCPT AND
			GRCCOH_MODCPT = CJRMVI.CJRMVI_MODCPT) = 'S' then
	RIGHT(REPLACE(CJRMVI_CHEQUE,' ','')+'0000000000000',13)
	ElSE SPACE(13)  END FLD030, -- NRO CHEQUE
SPACE (6) FLD031,
SPACE (40) FLD032,
SPACE (506) FLD033,
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,2) FLD080 /*Orden de Registro*/

FROM
	CJRMVI 
	INNER JOIN PVMPRH ON
	CJRMVI_NROCPV = PVMPRH_NROCTA
	INNER JOIN INRMSI on 
	INRMSI_CODTRA = @CODTRA AND
	INRMSI_NROLOT = @NROLOT AND
	INRMSI_TIPREG = 'A' AND
	INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE	
		CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY	CJRMVI_NROFOR,
			PVMPRH.PVMPRH_NROCTA,
			CJRMVI.CJRMVI_CODEMP,
			CJRMVI.CJRMVI_MODFOR,
			CJRMVI.CJRMVI_CODFOR,
			PVMPRH.PVMPRH_TIPDOC,
			PVMPRH.PVMPRH_NRODOC,
			CJRMVI.CJRMVI_CHEQUE,
			CJRMVI.CJRMVI_TIPCPT,
			CJRMVI.CJRMVI_CODCPT,
			CJRMVI.CJRMVI_MODCPT
