--/* Registro 070 

DECLARE @NROLOT NUMERIC (10), @CODTRA VARCHAR (12), @FCHEMI datetime, @FCHENT datetime,  @FCHPAG datetime, @ENVCHE VARCHAR (1), @ENVTRA VARCHAR (1), @CODEMP VARCHAR (6)
SET @NROLOT = '72'
SET @CODTRA = 'USR_PF'
SET @FCHEMI = '2018-09-20'
SET @FCHENT = '2018-09-20'
SET @FCHPAG = '2018-09-20'
SET @ENVCHE = 'S'
SET @ENVTRA = 'S'
SET @CODEMP = 'COTALT'
--*/

SELECT
'0306' FLD001,
'070' FLD002,
'CUIT' FLD003,
Replace((SELECT VALUE_STRING FROM CWPARAMETERS WHERE PARAMNAME = 'GR_NRCUIT' AND COMPANYNAME = @CODEMP),'-','') FLD004,
'@@@@@@' FLD005,
CONVERT(VARCHAR,PVROPH_FCHMOV,112) FLD006,
Right(SPACE(25)+PVROPH_TIPMOV +' - ' +PVROPH_CODRET,25) FLD007,
SPACE(1) FLD008,/*TIPO-COMP-IB*/
Right(PVROPH_NROAPL,8) FLD009,
REPLACE(SUM(PVROPH_IMPRET),'.','') FLD010,
SPACE(13) FLD011,/*BASE-IMPONIBLE*/
SPACE(5) FLD012,/*ALICUOTA-1-IB*/
SPACE(13) FLD013,/*IMPORTE-1-IB*/
SPACE(5)FLD014,/*ALICUOTA-2-IB*/
SPACE(13) FLD015,/*IMPORTE-2-IB*/
SPACE(5) FLD016,/*ALICUOTA-3-IB*/
SPACE(13) FLD017,/*IMPORTE-3-IB*/
'DB' FLD018,/*CODIGO-DB-CR*/
SPACE(692) FLD019, /*FILLER*/
(CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,5) FLD080 /*Orden de Registro*/

FROM CJRMVI 
INNER JOIN PVMPRH ON
CJRMVI_NROCPV = PVMPRH_NROCTA
INNER JOIN PVROPH ON CJRMVI_CODEMP = PVROPH_CODEMP
			  AND CJRMVI_MODFOR = 'CJ'
			  AND CJRMVI_CODFOR = PVROPH_CODFOR
			  AND CJRMVI_NROFOR = PVROPH_NROFOR
			  AND PVROPH_TIPRET = 'RB'

INNER JOIN INRMSI ON 
INRMSI_CODTRA = @CODTRA 
AND INRMSI_NROLOT = @NROLOT
AND INRMSI_TIPREG = 'A' 
AND INRMSI_FLD080 = (CJRMVI.CJRMVI_CODEMP + CJRMVI_MODFOR + CJRMVI_CODFOR + CONVERT(VARCHAR,CJRMVI_NROFOR))+CONVERT(VARCHAR,1) 

WHERE 
CJRMVI_CODEMP = @CODEMP AND
		CJRMVI_CODBCO = '017'
GROUP BY CJRMVI_CHEQUE,
		CJRMVI.CJRMVI_NROFOR,
		CJRMVI.CJRMVI_CODEMP,
		CJRMVI.CJRMVI_MODFOR,
		CJRMVI.CJRMVI_CODFOR,
		CJRMVI.CJRMVI_CODCPT,
		CJRMVI.CJRMVI_TIPCPT,
		CJRMVI.CJRMVI_MODCPT,
		PVROPH_IMPRET,
		PVROPH_NROAPL,
		PVROPH_FCHMOV,
		PVROPH_TIPMOV,
		PVROPH_CODRET,
		PVROPH_TIPRET